package Daje::Database::Model::CompaniesUsers;
use Mojo::Base 'Daje::Database::Model::Super::CompaniesUsers', -base, -signatures;

# Autogenerated class Sun Feb  2 14:05:15 2025
# This class is generated once. Any over rides or special methods should be put here





#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Model::CompaniesUsers


=head1 DESCRIPTION

Autogenerated class Sun Feb  2 14:05:15 2025
This class is generated once. Any over rides or special methods should be put here


=head1 REQUIRES

L<Mojo::Base> 


=head1 METHODS


=cut

