package Daje::Database::Model::CompanyType;
use Mojo::Base 'Daje::Database::Model::Super::CompanyType', -base, -signatures;

# Autogenerated class Sun Feb  2 14:05:15 2025
# This class is generated once. Any over rides or special methods should be put here




