package Daje::Database::Model::Super::Companies;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures;

# Autogenerated class Sun Feb  2 14:05:15 2025
# Any manual changes to this class will be overwritten next time its generated

has 'fields' => "'companies_pkey', 'editnum', 'insby', 'insdatetime', 'modby', 'moddatetime', 'company_type_fkey', 'homepage', 'name', 'phone', 'regno', 'vatno'";
has 'primary_key_name' => "companies_pkey";
has 'table_name' => "companies";



    sub load_pkey($companies_pkey) {

    my $result = $self->load_pk(
        $table_name,
        $fields,
        $primary_key_name,
        $companies_pkey
    );
    return $result;
}


    sub load_company_type_fkey($company_type_fkey ) {

    my $result = $self->load__fkey(
        $table_name,
        $fields,
        'company_type_fkey',
        $company_type_fkey
    );
    return $result;
}




    sub insert_companies($data) {
    my $result = $self->insert($table_name, $data);
    return $result;
}


    sub update_companies($data, $keys) {
    my $result = $self->update($table_name, $data, $keys)
    return $result;
}


    sub load_list($key_value) {
    my $result = $self->load_a_list(
        $table_name,
        $fields,
        $key_value
    );
    return $result;
}


    


