package Daje::Database::Model::Super::CompaniesUsers;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures;

# Autogenerated class Sun Feb  2 14:05:15 2025
# Any manual changes to this class will be overwritten next time its generated

has 'fields' => "'companies_users_pkey', 'editnum', 'insby', 'insdatetime', 'modby', 'moddatetime', 'companies_fkey', 'users_fkey'";
has 'primary_key_name' => "companies_users_pkey";
has 'table_name' => "companies_users";



    sub load_pkey($companies_users_pkey) {

    my $result = $self->load_pk(
        $table_name,
        $fields,
        $primary_key_name,
        $companies_users_pkey
    );
    return $result;
}


    sub load_companies_fkey($companies_fkey ) {

    my $result = $self->load__fkey(
        $table_name,
        $fields,
        'companies_fkey',
        $companies_fkey
    );
    return $result;
}



sub load_users_fkey($users_fkey ) {

    my $result = $self->load__fkey(
        $table_name,
        $fields,
        'users_fkey',
        $users_fkey
    );
    return $result;
}




    sub insert_companies_users($data) {
    my $result = $self->insert($table_name, $data);
    return $result;
}


    sub update_companies_users($data, $keys) {
    my $result = $self->update($table_name, $data, $keys)
    return $result;
}


    sub load_list($key_value) {
    my $result = $self->load_a_list(
        $table_name,
        $fields,
        $key_value
    );
    return $result;
}


    



#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Model::Super::CompaniesUsers


=head1 DESCRIPTION

Autogenerated class Sun Feb  2 14:05:15 2025
Any manual changes to this class will be overwritten next time its generated


=head1 REQUIRES

L<Mojo::Base> 


=head1 METHODS

=head2 insert_companies_users($data)

 insert_companies_users($data)();

=head2 load_companies_fkey($companies_fkey

 load_companies_fkey($companies_fkey();

=head2 load_list($key_value)

 load_list($key_value)();

=head2 load_pkey($companies_users_pkey)

 load_pkey($companies_users_pkey)();

=head2 load_users_fkey($users_fkey

 load_users_fkey($users_fkey();

=head2 update_companies_users($data,

 update_companies_users($data,();


=cut

