package Daje::Database::Model::Super::Users;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures;

# Autogenerated class Sun Feb  2 14:05:15 2025
# Any manual changes to this class will be overwritten next time its generated

has 'fields' => "'users_pkey', 'editnum', 'insby', 'insdatetime', 'modby', 'moddatetime', 'active', 'is_admin', 'password', 'phone', 'support', 'userid', 'username'";
has 'primary_key_name' => "users_pkey";
has 'table_name' => "users";



    sub load_pkey($users_pkey) {

    my $result = $self->load_pk(
        $table_name,
        $fields,
        $primary_key_name,
        $users_pkey
    );
    return $result;
}


    
    sub insert_users($data) {
    my $result = $self->insert($table_name, $data);
    return $result;
}


    sub update_users($data, $keys) {
    my $result = $self->update($table_name, $data, $keys)
    return $result;
}


    sub load_list($key_value) {
    my $result = $self->load_a_list(
        $table_name,
        $fields,
        $key_value
    );
    return $result;
}


    


