package Daje::Database::Controller::Pgupdate;
use Mojo::Base 'Daje::Database::Controller::BaseController';

use Daje::Database::Helper::Common;

sub update($self) {

    $self->render_later;
    my $data = Daje::Database::Helper::Common->new($self)->get_basedata();
}

1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Controller::Pgupdate


=head1 REQUIRES

L<Daje::Database::Helper::Common> 

L<Mojo::Base> 


=head1 METHODS

=head2 update($self)

 update($self)();


=cut

