package Daje::Database::Helper::Instring;
use Mojo::Base  -base, -signatures;



sub build_in_string($self, $list) {

    my $result = "";
    my $length = scalar @{ $list };
    for (my $i = 0; $i < $length; $i++) {
        my $field = @{ $list }[$i]->{table_name};
        if ($i == $length - 1) {
            $result .= "'" . $field . "'";
        } else {
            $result .= "'" . $field  . "'" . ", ";
        }
    }

    $result = 'mojo_migrations' unless $result;
    return $result;
}
1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Helper::Instring


=head1 REQUIRES

L<Mojo::Base> 


=head1 METHODS

=head2 build_in_string($self,

 build_in_string($self,();


=cut

